# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Vidushi Gupta
tagline:          Online portfolio
description:      'Trying to put my portfolio online ğŸ˜„'
baseurl:          /

paginate:         2
